[package]
name = "jtr-demo"
version = "0.1.0"
edition = "2021"
default-run = "jtr-demo"

[dependencies]
rand = "0.8.5"
rand_chacha = { version = "0.3.1", features = ["simd"] }
rayon = "1.10.0"
sha2 = "0.10.8"
