[package]
name = "jtr-demo"
version = "0.1.0"
edition = "2021"
default-run = "jtr-demo"

[dependencies]
kanal = "0.1.0-pre8"
md-5 = "0.10.6"
rand = "0.8.5"
rand_chacha = { version = "0.3.1", features = ["simd"] }
rayon = "1.10.0"
tokio = {version = "1.41.1",features = ["full"]}


